timit_to_cmu = {
    'zh': 'sh',
    'em': 'm',
    'en': 'n',
    'eng': 'ng',
    'nx': 'n',
    'hv': 'hh',
    'el': 'l',
    'ao': 'aa',
    'ux': 'uw',
    'ax': 'ah',
    'ix': 'ih',
    'axr': 'er',
    'ax-h': 'ah',
    'q': 'rest',
    'kcl': 'rest',
    'gcl': 'rest',
    'tcl': 'rest',
    'pcl': 'rest',
    'dcl': 'rest',
    'bcl': 'rest',
    'pau': 'rest',
    'epi': 'rest',
    'h#': 'rest'
}

phoneme_code = {
    'b': 0,
    'd': 1,
    'g': 2,
    'p': 3,
    't': 4,
    'k': 5,
    'dx': 6,
    'q': 7,
    'jh': 8,
    'ch': 9,
    's': 10,
    'sh': 11,
    'z': 12,
    'zh': 13,
    'f': 14,
    'th': 15,
    'v': 16,
    'dh': 17,
    'm': 18,
    'n': 19,
    'ng': 20,
    'em': 21,
    'en': 22,
    'eng': 23,
    'nx': 24,
    'l': 25,
    'r': 26,
    'w': 27,
    'y': 28,
    'hh': 29,
    'hv': 30,
    'el': 31,
    'iy': 32,
    'ih': 33,
    'eh': 34,
    'ey': 35,
    'ae': 36,
    'aa': 37,
    'aw': 38,
    'ay': 39,
    'ah': 40,
    'ao': 41,
    'oy': 42,
    'ow': 43,
    'uh': 44,
    'uw': 45,
    'ux': 46,
    'er': 47,
    'ax': 48,
    'ix': 49,
    'axr': 50,
    'ax-h': 51,
    'kcl': 52,
    'gcl': 53,
    'tcl': 54,
    'pcl': 55,
    'dcl': 56,
    'bcl': 57,
    'pau': 58,
    'epi': 59,
    'h#': 60
}

code_phoneme = {v: k for k, v in phoneme_code.items()}


def get_cmu_phoneme(timit_phoneme):
    if timit_phoneme in timit_to_cmu.keys():
        return timit_to_cmu[timit_phoneme]
    else:
        return timit_phoneme
